set -x

PROJECT_NAME="M3"
EXPERIMENT_NAME="LingShu-7B"
export WANDB_API_KEY=debf45c8d5066727456db660e57400d78b751446
export WANDB_MODE=offline
export SAVE_CHECKPOINT_DIR=/volume/pt-train/users/txie/misc/CKPT/M3-Lingshu7B
# export VLLM_ATTENTION_BACKEND=XFORMERS # vllm + qwen2-7b with flash_attn has some issues
export LLM_AS_A_JUDGE_BASE="http://172.16.43.156:18900/v1"
BASEDIR=/volume/pt-train/users/txie/misc/Data/M3/Train
EvBASEDIR=/volume/pt-train/users/txie/misc/Data/M3/Test
# VISUAL_DATASET_TRAIN_0_6_2=${BASEDIR}/data_v0.6.2_reason.parquet
Data1=$BASEDIR/path_vqa_converted_final1.parquet
Data2=$BASEDIR/pmc_vqa_converted1.parquet
# VISUAL_DATASET_TEST=${BASEDIR}/seekworld_test.parquet
Data3=$BASEDIR/slake_converted1.parquet
Data4=$BASEDIR/vqa_rad_converted_final1.parquet

Data5=$BASEDIR/path_vqa_converted_final2.parquet
Data6=$BASEDIR/pmc_vqa_converted2.parquet
# VISUAL_DATASET_TEST=${BASEDIR}/seekworld_test.parquet
Data7=$BASEDIR/slake_converted2.parquet
Data8=$BASEDIR/vqa_rad_converted_final2.parquet

Eval_path1=$EvBASEDIR/pmc_vqa_converted.parquet
Eval_path2=$EvBASEDIR/slake_converted.parquet
REF_MODEL_PATH=/volume/pt-train/users/txie/misc/Model/Lingshu-7B
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    +debug=False \
    +vs_debug=False \
    data.train_files=[${Data1},${Data2},${Data3},${Data4},${Data5},${Data6},${Data8}] \
    data.val_files=[${Eval_path1},${Eval_path2}] \
    data.train_batch_size=256 \
    data.max_prompt_length=16384 \
    data.max_response_length=20480 \
    data.return_raw_chat=True \
    data.filter_overlong_prompts=True \
    algorithm.adv_estimator=grpo \
    algorithm.kl_ctrl.kl_coef=0.0 \
    actor_rollout_ref.model.path=${REF_MODEL_PATH} \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=256 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.checkpoint.contents=['model','hf_model','optimizer','extra'] \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.n=16 \
    actor_rollout_ref.rollout.max_num_batched_tokens=32768 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.rollout.agent.activate_agent=True \
    actor_rollout_ref.rollout.agent.tool_name_key=env_name \
    actor_rollout_ref.rollout.agent.single_response_max_tokens=10240 \
    actor_rollout_ref.rollout.agent.max_turns=5 \
    actor_rollout_ref.rollout.agent.concurrent_workers=1 \
    actor_rollout_ref.rollout.agent.show_tqdm=True \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb','rl_logging_board'] \
    trainer.val_before_train=False \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=${WORLD_SIZE} \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.project_name=${PROJECT_NAME} \
    trainer.experiment_name=${EXPERIMENT_NAME} \
    trainer.default_local_dir=${SAVE_CHECKPOINT_DIR}/${PROJECT_NAME}/${EXPERIMENT_NAME} \
    +trainer.tensorboard_dir=${SAVE_CHECKPOINT_DIR}/logs/tensorboard \
    +trainer.rl_logging_board_dir=${SAVE_CHECKPOINT_DIR}/logs/rl_logging_board \
    trainer.total_epochs=1 2>&1 | tee ./logs/${EXPERIMENT_NAME}.log
